// packages/demo-react/src/App.tsx
import { useEffect, useRef, useState } from 'react';
import { BrowserTerminal } from 'browser-terminal';
import { useCommand } from './useTerminal';
import { ansiToHtml, highlight, region } from './code';
// Shown on the page verbatim, so the example can't drift from the code.
import hookSource from './useTerminal.ts?raw';
import appSource from './App.tsx?raw';

export interface Task {
  id: number;
  title: string;
  done: boolean;
  priority: number;
}

/** Commands whose generated help is shown at the bottom of the page. */
const HELP_FOR = ['task add', 'task done'];

const SEED: Task[] = [
  { id: 1, title: 'wire up the terminal', done: true, priority: 2 },
  { id: 2, title: 'drive React state from a pipeline', done: false, priority: 3 },
  { id: 3, title: 'compare with Svelte', done: false, priority: 1 },
];

function CodeBlock({
  title,
  source,
  name,
  tone,
}: {
  title: string;
  source: string;
  name: string;
  tone?: 'bad';
}) {
  return (
    <details className={tone === 'bad' ? 'code bad' : 'code'} open>
      <summary>{title}</summary>
      <pre>
        <code dangerouslySetInnerHTML={{ __html: highlight(region(source, name)) }} />
      </pre>
    </details>
  );
}

export function App() {
  const [bt, setBt] = useState<BrowserTerminal | null>(null);
  const [tasks, setTasks] = useState<Task[]>(SEED);
  const nextId = useRef(SEED.length + 1);

  useEffect(() => {
    let live = true;
    let created: BrowserTerminal | null = null;
    BrowserTerminal.create({ globalToggle: true }).then((t) => {
      // StrictMode double-mounts in dev; drop the instance if we already
      // unmounted, or the singleton guard will reject the next create().
      if (!live) {
        t.dispose();
        return;
      }
      created = t;
      setBt(t);
      // For devtools poking and the CI boot check.
      (window as unknown as { bt: BrowserTerminal }).bt = t;
    });
    return () => {
      live = false;
      created?.dispose();
    };
  }, []);

  // --- commands, all reading/writing live component state ---

  // #region commands
  // `task list` reads live component state; `task add` writes it. The hook
  // keeps a ref to the latest closure, so these always see current state
  // without re-registering on every render.
  //
  // A name with a space in it *is* the subcommand mechanism: registering
  // `task list` and `task add` makes `task` a group, so bare `task` lists
  // them. There is no group object to declare — no `add_subparsers()`, no
  // parent to attach to.
  //
  // The `summary` and `desc` strings are the command's documentation:
  // `task add --help` renders them. Nothing registers `--help` — the
  // evaluator intercepts it before binding, so the help page is whatever
  // this signature says.
  useCommand(bt, { name: 'task list', summary: 'Show the current task list' }, () => tasks);

  useCommand(
    bt,
    {
      name: 'task add',
      summary: 'Add a task to the list',
      required: [{ name: 'title', shape: 'str', desc: 'what needs doing' }],
      flags: [
        { long: 'priority', short: 'p', shape: 'int', desc: 'urgency, 1 (low) to 3 (high)' },
        { long: 'done', short: 'd', desc: 'add it already checked off' },
      ],
    },
    ({ positionals, flags }) => {
      const task: Task = {
        id: nextId.current++,
        title: String(positionals[0]),
        done: Boolean(flags.done),
        priority: Number(flags.priority ?? 1),
      };
      setTasks((t) => [...t, task]);
      return task;
    },
  );
  // #endregion

  useCommand(
    bt,
    {
      name: 'task done',
      summary: 'Check a task off (or back on)',
      required: [{ name: 'id', shape: 'int', desc: 'the id shown in the # column' }],
    },
    ({ positionals }) => {
      const id = Number(positionals[0]);
      if (!tasks.some((t) => t.id === id)) {
        throw { message: `no task ${id}`, help: 'run `task list` to see ids' };
      }
      setTasks((t) => t.map((x) => (x.id === id ? { ...x, done: !x.done } : x)));
      return null;
    },
  );

  useCommand(
    bt,
    {
      name: 'task rm',
      summary: 'Remove a task from the list',
      required: [{ name: 'id', shape: 'int', desc: 'the id shown in the # column' }],
    },
    ({ positionals }) => {
      const id = Number(positionals[0]);
      setTasks((t) => t.filter((x) => x.id !== id));
      return null;
    },
  );

  // #region stale
  // BROKEN ON PURPOSE — this is the mistake `useCommand` exists to prevent.
  //
  // The command is registered once, so it captures `tasks` from the render
  // that registered it and reports that forever. Adding a task updates the
  // component but not this closure.
  //
  // Note the eslint-disable: react-hooks/exhaustive-deps *does* catch this,
  // and we had to silence it to keep the bug. Listening to the linter and
  // adding `tasks` to the deps fixes the staleness but re-registers on every
  // render — which is why the hook keeps a ref instead.
  useEffect(() => {
    if (!bt) return;
    bt.registerCommand(
      { name: 'task stale', summary: 'BROKEN on purpose: the stale-closure demo' },
      () => tasks,
    );
    return () => bt.unregisterCommand('task stale');
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [bt]); // <- no `tasks` dep: this is the bug being demonstrated
  // #endregion

  // #region help
  // Nothing here registers `--help`. Asking the engine for it — rather than
  // pasting the output into the page — means what a visitor reads is
  // generated from the signatures above and can't drift from them.
  //
  // This effect is declared *after* the useCommand calls on purpose: effects
  // in one component run in declaration order, so the commands exist by the
  // time we ask them to describe themselves.
  const [help, setHelp] = useState<string[]>([]);
  useEffect(() => {
    if (!bt) return;
    let live = true;
    Promise.all(HELP_FOR.map((c) => bt.run(`${c} --help`))).then((texts) => {
      if (live) setHelp(texts.map((t) => ansiToHtml(String(t).trimEnd())));
    });
    return () => {
      live = false;
    };
  }, [bt]);
  // #endregion

  const remaining = tasks.filter((t) => !t.done).length;

  return (
    <main>
      <h1>
        browser-terminal <span className="x">×</span> React
      </h1>
      <p className="lede">
        Every command below reads and writes this component's <code>useState</code>.
        Type in the terminal panel and watch the list change.
      </p>

      <ul className="tasks">
        {tasks.map((t) => (
          <li key={t.id} className={t.done ? 'done' : ''}>
            <span className="id">#{t.id}</span>
            <span className="title">{t.title}</span>
            <span className={`pri p${t.priority}`}>P{t.priority}</span>
          </li>
        ))}
        {tasks.length === 0 && <li className="empty">no tasks — try `task add 'something'`</li>}
      </ul>
      <p className="count">
        {remaining} remaining / {tasks.length} total
      </p>

      <h2>Try</h2>
      <pre>
{`task               # a group: lists its subcommands
task add --help    # every command gets this for free
task add 'ship it' --priority 3
task add 'already did this' --done
task list | filter {|t| !$t.done}
task list | sort-by priority --reverse | head 2
task list | filter {|t| $t.priority > 1} | map {|t| $t.title}
task done 2

task stale         # broken on purpose — still shows the seed list`}
      </pre>
      <h2>How it's implemented</h2>
      <p className="sub">
        Extracted from this page's own source at build time — not a
        transcription.
      </p>
      <CodeBlock title="Registering commands over useState" source={appSource} name="commands" />
      <CodeBlock
        title="✗ The trap: registering the naive way (this is `task stale`)"
        source={appSource}
        name="stale"
        tone="bad"
      />
      <CodeBlock title="The useCommand hook (latest-ref pattern)" source={hookSource} name="hook" />

      <h2>What that buys you</h2>
      <p className="sub">
        No command registers a <code>--help</code> flag. The evaluator intercepts
        it before argument binding and renders the signature, so these pages come
        from the <code>summary</code> and <code>desc</code> strings above —
        printed by the live engine on this page, not pasted in.
      </p>
      {help.map((html, i) => (
        <details className="code help" open key={HELP_FOR[i]}>
          <summary>{HELP_FOR[i]} --help</summary>
          <pre>
            <code dangerouslySetInnerHTML={{ __html: html }} />
          </pre>
        </details>
      ))}
      <CodeBlock title="Asking the engine for its own help text" source={appSource} name="help" />

      <p className="note">
        <code>task list</code> uses the <code>useCommand</code> latest-ref hook, so it
        always sees current state. <code>task stale</code> was registered the naive way
        and is frozen at mount — the trap the hook exists to solve. Both are in the same
        group, so <code>task</code> lists them side by side.
      </p>
    </main>
  );
}

// packages/demo-svelte/src/App.svelte
<script lang="ts">
  import { store } from './tasks.svelte';
  import { helpPages } from './help.svelte';
  import { highlight, region } from './code';
  // Real source, extracted at build time — the example can't drift.
  import commandsSource from './commands.ts?raw';
  import storeSource from './tasks.svelte.ts?raw';

  const panels = [
    ['Registering commands over a rune store', commandsSource, 'commands'],
    ['The store itself (module-level $state)', storeSource, 'store'],
  ] as const;

  // Derived from the same signal the shell commands mutate.
  const remaining = $derived(store.tasks.filter((t) => !t.done).length);
</script>

<main>
  <h1>browser-terminal <span class="x">×</span> Svelte</h1>
  <p class="lede">
    These commands read and write a module-level <code>$state</code> rune — registered
    once at startup, with no hooks, refs, or cleanup.
  </p>

  <ul class="tasks">
    {#each store.tasks as task (task.id)}
      <li class:done={task.done}>
        <span class="id">#{task.id}</span>
        <span class="title">{task.title}</span>
        <span class="pri p{task.priority}">P{task.priority}</span>
      </li>
    {:else}
      <li class="empty">no tasks — try `task add 'something'`</li>
    {/each}
  </ul>
  <p class="count">{remaining} remaining / {store.tasks.length} total</p>

  <h2>Try</h2>
  <pre>{`task               # a group: lists its subcommands
task add --help    # every command gets this for free
task add 'ship it' --priority 3
task add 'already did this' --done
task list | filter {|t| !$t.done}
task list | sort-by priority --reverse | head 2
task list | map @slug
task done 2`}</pre>
  <h2>How it's implemented</h2>
  <p class="sub">Extracted from this page's own source at build time — not a transcription.</p>
  {#each panels as [title, source, name] (name)}
    <details class="code" open>
      <summary>{title}</summary>
      <pre><code>{@html highlight(region(source, name))}</code></pre>
    </details>
  {/each}

  <h2>What that buys you</h2>
  <p class="sub">
    No command registers a <code>--help</code> flag. The evaluator intercepts it
    before argument binding and renders the signature, so these pages come from
    the <code>summary</code> and <code>desc</code> strings above — printed by the
    live engine on this page, not pasted in.
  </p>
  {#each helpPages as page (page.command)}
    <details class="code help" open>
      <summary>{page.command} --help</summary>
      <pre><code>{@html page.html}</code></pre>
    </details>
  {/each}

  <p class="note">
    Compare with the React demo on :5174 — there, commands must reach state through a
    latest-ref hook, because <code>useState</code> is scoped to a render. A Svelte rune
    lives outside the component, so the shell can just hold it.
  </p>
</main>

<style>
  :global(:root) {
    color-scheme: dark;
  }
  :global(body) {
    margin: 0;
    background: #11111b;
    color: #cdd6f4;
    font: 15px/1.6 system-ui, sans-serif;
  }
  main {
    max-width: 680px;
    margin: 3rem auto;
    padding: 0 1.25rem 4rem;
  }
  h1 {
    font-size: 1.5rem;
    margin-bottom: 0.25rem;
  }
  .x {
    color: #9399b2;
  }
  h2 {
    font-size: 1rem;
    margin-top: 2rem;
    color: #9399b2;
    text-transform: uppercase;
    letter-spacing: 0.08em;
  }
  .lede {
    color: #9399b2;
    margin-top: 0;
  }
  code,
  pre {
    font-family: ui-monospace, SFMono-Regular, Menlo, monospace;
    font-size: 13px;
  }
  pre {
    background: #181825;
    border: 1px solid #313244;
    border-radius: 8px;
    padding: 0.85rem 1rem;
    overflow-x: auto;
    color: #a6e3a1;
  }
  .tasks {
    list-style: none;
    padding: 0;
    margin: 1.5rem 0 0.5rem;
    border: 1px solid #313244;
    border-radius: 8px;
    overflow: hidden;
  }
  .tasks li {
    display: flex;
    align-items: center;
    gap: 0.75rem;
    padding: 0.6rem 0.9rem;
    border-bottom: 1px solid #313244;
  }
  .tasks li:last-child {
    border-bottom: none;
  }
  .tasks li.done .title {
    text-decoration: line-through;
    color: #9399b2;
  }
  .tasks li.empty {
    color: #9399b2;
    font-style: italic;
  }
  .id {
    color: #9399b2;
    font-family: ui-monospace, monospace;
    font-size: 12px;
    min-width: 2.2rem;
  }
  .title {
    flex: 1;
  }
  .pri {
    font-family: ui-monospace, monospace;
    font-size: 11px;
    padding: 1px 7px;
    border-radius: 999px;
    border: 1px solid #313244;
    color: #9399b2;
  }
  .pri.p3 {
    color: #f38ba8;
    border-color: #f38ba8;
  }
  .pri.p2 {
    color: #f9e2af;
    border-color: #f9e2af;
  }
  .count {
    color: #9399b2;
    font-size: 13px;
    margin: 0;
  }
  .note {
    color: #9399b2;
    font-size: 13px;
  }
  .sub {
    color: #6c7086;
    font-size: 13px;
    margin-top: -0.4rem;
  }
  details.code {
    border: 1px solid #313244;
    border-radius: 8px;
    background: #181825;
    margin: 0.75rem 0;
    overflow: hidden;
  }
  details.code > summary {
    cursor: pointer;
    padding: 0.6rem 0.9rem;
    font-size: 0.85rem;
    user-select: none;
  }
  details.code > summary:hover { background: #1e1e2e; }
  details.code pre {
    margin: 0;
    padding: 0.9rem;
    border-top: 1px solid #313244;
    border-radius: 0;
    color: #cdd6f4;
  }
  details.code code { font-size: 12.5px; line-height: 1.55; white-space: pre; }
  /* The engine's own SGR codes, as emitted by the help renderer. */
  details.help :global(.hb) { font-weight: 600; font-style: normal; }
  details.help :global(.hd) { color: #6c7086; font-style: normal; }
  details.help :global(.hc) { color: #89dceb; font-style: normal; }
  details.help > summary {
    font-family: ui-monospace, SFMono-Regular, Menlo, monospace;
    color: #a6e3a1;
  }
  details.code :global(.c) { color: #6c7086; font-style: normal; }
  details.code :global(.s) { color: #a6e3a1; font-style: normal; }
  details.code :global(.k) { color: #cba6f7; font-style: normal; }
</style>
